### ISSUE TITLE
calendar uri & hmac-key files not documented

### ISSUE THREAD

**Issue by cisba** [opentimestamps/opentimestamps-server#18]
First run requires two undocumented files in the calendar directory: uri & hmac-key.

I suppose for uri something like this:

`http://myhost:port/path?query`

But a working example is very useful.

I suppose that hmac-key should be generated with something like this:
```
import hmac
import hashlib
import base64
dig = hmac.new(b'secret', msg=bytes_string, digestmod=hashlib.sha256).digest()
base64.b64encode(dig).decode() 
```

Where 'secret' is a password and bytes_string is the string saved inside the uri file above.

**Comment by petertodd** [comment]
Noted, thanks!

Yes, the entire process of running a calendar - and *when* you should run a calendar - isn't really documented. I'll leave this issue open until it is.

**Comment by miderose** [comment]
+1

I'm trying to start an opentimestamps server but I'm not able to find documentation even on how to start!

I'm now experienced this:
> Calendar URI not yet set; '/home/michele/.otsd/calendar/uri' does not exist

what has to be in this file? (...my bitcoin node URI?)

**Comment by petertodd** [comment]
Basically whatever is in that file is put into the URI field of pending attestations returned by that calendar server. So when a client goes to verify a timestamp created by that calendar, if the URI starts with `http` or `https`, it'll try to make a HTTP(S) connection to that server to fetch the rest of the timestamp proof.

E.g. the `alice.btc.calendar.opentimestamps.org` calendar server has `https://alice.btc.calendar.opentimestamps.org` in the `~/.otsd/calendar/uri` file.

**Comment by cisba** [comment]
Everything is now explained in the Readme.md file.
