### ISSUE TITLE
Unconfirmed txs clearing

### ISSUE THREAD

**Issue by RCasatta** [opentimestamps/opentimestamps-server#25]
Is possible that the folllowing line:
https://github.com/opentimestamps/opentimestamps-server/blob/b0bdfe666bc9801c3242e16f76b45c8572c74714/otsserver/stamper.py#L272

Isn't considering the case where someone else is doing the transaction for the calendar but the digest is older than the most recent?
In that case we should probably remove only all the older than the current unconfirmed_tx (because the external tx is not conflicting with the calendar one)

**Comment by petertodd** [comment]
Good point! I think you're right.

Maybe replace that with:

    self.unconfirmed_txs = self.unconfirmed_txs[i+1:]

where `i` is the index of the unconfirmed tx found?

**Comment by RCasatta** [comment]
sure, doing the commit to fix in the current PR https://github.com/opentimestamps/opentimestamps-server/pull/24

**Comment by RCasatta** [comment]
Done, since I am looping `self.unconfirmed_txs` in reverse order I used `[0:i]`
