### ISSUE TITLE
Connection with multichain

### ISSUE THREAD

**Issue by oury1** [opentimestamps/opentimestamps-server#27]
Hi everyone 
I want to use opentimestamp with private blockchain.
For the private blockchain i use Multichain .
someone can help with integrate opentimestamp and multichain

thanks

**Comment by petertodd** [comment]
Why do you want to use OpenTimestamps with a private blockchain? What are you trying to prove exactly?

**Comment by oury1** [comment]
Hi peter thanks for your response 
I want to use private blockchain to make a faster timestamping and keep it private with a shared private blockchain

**Comment by petertodd** [comment]
This would probably be more useful to you: https://lists.opentimestamps.org/pipermail/ots-dev/2017-May/000001.html

**Comment by oury1** [comment]
Hi Peter thanks for your response
I don't need to do a more secure timestamping but a more often timestamping
I think that using multichain it could be easy because multichain use the
same protocol of bitcoin
Can you have a look few minutes
Thanks
