### ISSUE TITLE
Attestation pending for over two days

### ISSUE THREAD

**Issue by yerofeyev** [opentimestamps/opentimestamps-server#28]
Here's the attestation I submitted, still pending in all the three calendars: 

[Attestation](https://opentimestamps.org/info.html?ots=004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108ccccd32f1a9b2d99c9e5cde3c801b986ca366b9a5e5c4182b31750cd9bc85fe8f010de7d0200c0313adfc77fbc9cfa63d51f08fff010a3680171972a12b66cb706edc1c564fd08f1045a62878df008e68379af2a7edd2a0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0107061231bf23061d0f620e5c115f22eea08f1045a62878bf008e37428bc5d3223ab0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f01037073c02085440048b01420a1a572d6c08f1045a62878cf00812ccb875aaac51500083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

**Comment by petertodd** [comment]
Strange, I just tried verifying that timestamp and it works fine here.

What exact commands were you using?

**Comment by yerofeyev** [comment]
I'm checking in the browser (keeping the tab open) and also using 
`ots info`

<img width="502" alt="screen shot 2018-01-21 at 7 28 30 pm" src="https://user-images.githubusercontent.com/4384462/35204193-55ea20d0-fee1-11e7-9686-7802aae90368.png">

**Comment by petertodd** [comment]
Ah, yeah, I think I need to change the name of `PendingAttestation`...

If you try `ots verify` or `ots upgrade` you'll see that your timestamp has been completed; the `ots info` command is just a dump of the timestamp proof file contents; it doesn't check the calendar servers to see if they've finished.

**Comment by yerofeyev** [comment]
Perfect, thanks!

**Comment by petertodd** [comment]
https://lists.opentimestamps.org/pipermail/ots-dev/2018-January/000036.html
