### ISSUE TITLE
Question - Frequency of transactions

### ISSUE THREAD

**Issue by InnovativeInventor** [opentimestamps/opentimestamps-server#38]
Just curious, how many minutes/how many requests does it take for an opentimestamps server to start a bitcoin transaction? Is it hourly or based upon the number of waiting proofs?

**Comment by InnovativeInventor** [comment]
Yeah. I was wondering how long it would take until a proof becomes irreversible. This would be great for making a nothing up my sleeve number. If you submit a proof of your code, then use the next few hashMerkleRoots in the next few blocks as a seed for an open-sourced CSPRNG, you will have a perfect nothing up my sleeve number. This might be useful for neural cryptography to prove transparency.

**Comment by petertodd** [comment]
Ah, what you want is called a "random beacon"

A good way to do that is iterated hashing, as Zcash recently did: https://lists.z.cash.foundation/pipermail/zapps-wg/2018/000337.html

That's not a novel technique BTW: you can dig up few academic papers proving it's a good idea. Though their use of OpenTimestamps in it added little, if any, security: https://lists.z.cash.foundation/pipermail/zapps-wg/2018/000339.html

**Comment by InnovativeInventor** [comment]
Amazing! The Zcash community sounds amazing! Using opentimestamps proves that you picked a block height beforehand, preventing attackers from influencing the number by cherry picking a suitable block.

**Comment by petertodd** [comment]
No it doesn't: you could have chosen multiple blocks, and timestamped multiple messages committing to each one, then revealed the one that was best for you after the fact.

**Comment by InnovativeInventor** [comment]
Good point! I was thinking the order would be more like this:
1. Create code and find a suitable block height
2. Timestamp and sign it
3. Publish and distribute it to many people (maybe even put a signed copy within the bitcoin blockchain if you want to skip step 2 and be 100% sure)
4. Then, when the blockchain reaches that height, it is used to generate random data.

If anyone is able to produce a signed version of the machine learning code that conflicts, then you know something fishy is happening. It would be very tedious and hard to generate enough signed copies, publish and announce each copy and somehow keep people from finding out that you are distributing many different copies of your program. This might not be easy for every single machine learning model, but would be somewhat practical for huge projects.

**Comment by dgpv** [comment]
>  The servers actually work by spending a fixed budget

Could it be possible to temporary increase this budget by sending a certain sum (can call it a "donation", if it is a public service) to specific address ?

**Comment by petertodd** [comment]
@dgpv Actually Lightning could work well for that these days; the fee is just a tx fee, so sending a tx is likely to be inefficient unless we're doing so in a way that's actually making us money.

**Comment by cisba** [comment]
@petertodd, you wrote:
"The servers actually work by spending a fixed budget, which means the time between timestamps changes as fees change. Currently it looks like they're doing a few a day, but on occasion I've seen it go down to once a day or so."

Today I think the stamper frequency depends from the parameter --btc-min-tx-interval 
Is it correct?
