### ISSUE TITLE
Missing Hardware Requirements

### ISSUE THREAD

**Issue by emanuelr93** [opentimestamps/opentimestamps-server#42]
Can you add Hardware Requirements of OpenTimestamps Server?
I need also some details about High Availability of Server.

**Comment by petertodd** [comment]
There kinda aren't really any specific requirements; it'd run on basically any hardware that is sufficient to run a standard Linux distribution.

**Comment by emanuelr93** [comment]
Ok, 
for high availability? What i should do to have a 2 aligned load balance istance? 

Thank you

**Comment by petertodd** [comment]
OTS is designed with redundancy in mind. Only one calendar server needs to work for a timestamp to be valid, so for high availability simply use multiple calendar servers.

This is how it works by default using the public ones; unless you have a good reason not too I always recommend using them, with the default configuration.
