### ISSUE TITLE
signrawtransaction is deprecated and will be fully removed in v0.18

### ISSUE THREAD

**Issue by certifirm** [opentimestamps/opentimestamps-server#45]
I must init bitcoin with -> bitcoind --daemon -deprecatedrpc=signrawtransaction

`bitcoin.rpc.JSONRPCError: {'code': -32, 'message': 'signrawtransaction is deprecated and will be fully removed in v0.18. To use signrawtransaction in v0.17, restart bitcoind with -deprecatedrpc=signrawtransaction.\nProjects should transition to using signrawtransactionwithkey and signrawtransactionwithwallet before upgrading to v0.18'}`

**Comment by petertodd** [comment]
Yeah, this needs to be fixed at some point.

**Comment by petertodd** [comment]
Fixed as of v0.6.0
