### ISSUE TITLE
getaccountaddress is deprecated and will be fully removed in v0.18

### ISSUE THREAD

**Issue by cisba** [opentimestamps/opentimestamps-server#56]
From 0.17.x the rpc module fails calling getaccountaddress method and the web ui result blank to the user.

**Comment by petertodd** [comment]
Oh! To be clear, that's running 0.17.1 like the README suggests? Is that fixed by adding getaccountaddress to the depreciatedrpc list in bitcoin.conf?

Kinda odd, as I'm running my calenders with 0.17.1

**Comment by petertodd** [comment]
Oh sorry, I see what you mean in your pull-req: 0.17.1 works, but 0.18 doesn't.

**Comment by petertodd** [comment]
Fixed as of https://github.com/opentimestamps/opentimestamps-server/tree/opentimestamps-server-v0.6.0
