### ISSUE TITLE
How to start a mirror server

### ISSUE THREAD

**Issue by santillaner** [opentimestamps/opentimestamps-server#61]
Hi there!

Just wondering if it is possible to have a local server with mirrored data por upgrading the OTS's. I've seen the real-time requirement in the TODO file in the future, but I do not really have real-time requirements, i.e., it would fine for me to upgrade only files that are a couple of days old, and I would be more than willing to run a mirror on my internal network so that I do not send too much traffic to your servers. 

Is there a way to do this? We are currently sending too many upgrade requests so we are having too many rejections. ¿Is there a better way to do the upgrades that to call the calendar server with every its?

BTW, thank you guys for a great library :-)

Cheers, 

Manuel

**Comment by santillaner** [comment]
BTW, I've tried to ```wget --no-parent -Nr https://bob.btc.calendar.opentimestamps.org/calendar``` and the other wget's of https://github.com/opentimestamps/opentimestamps-client/blob/master/contrib/calendar-mirror.sh but I get 404

**Comment by petertodd** [comment]
On Mon, Sep 09, 2019 at 06:51:08AM -0700, santillaner wrote:
> BTW, I've tried to ```wget --no-parent -Nr https://bob.btc.calendar.opentimestamps.org/calendar``` and the other wget's of https://github.com/opentimestamps/opentimestamps-client/blob/master/contrib/calendar-mirror.sh but I get 404

Have you tried the `otsd-backup.py` script from `opentimestamps-server`? That's
the best way to do it now.

I do want to improve this by adding a proper blockchain scheme to this. But
that's going to take some time.

**Comment by santillaner** [comment]
Thanks Peter!

I'll give it a try and let you know

Cheers!
