### ISSUE TITLE
Using Bitcoin Core 0.19.0

### ISSUE THREAD

**Issue by PatrickLemke** [opentimestamps/opentimestamps-server#73]
Is supporting newer Bitcoin Core versions planned? Is it possible to get it to work with an already running instance of Bitcoin Core 0.19.0?

**Comment by RCasatta** [comment]
As fare as I know there is no plan to support bitcoin 0.19.0.
We support only 0.17.1 and you don't need all the blockchain you can use a pruned node.

**Comment by petertodd** [comment]
I mean, I certainly think 0.19.0 support is a good thing. It's just there's very few people actually running OpenTimestamps calendars so actually implementing that isn't high on my priority list.

**Comment by insidenothing** [comment]
I can say 0.17.1 pruned node still works fine on a new install. considering how often they release new versions https://bitcoincore.org/bin/ i am ok not doing that all the time.
