### ISSUE TITLE
Question about using a pruned node

### ISSUE THREAD

**Issue by GTP95** [opentimestamps/opentimestamps-server#74]
Hello everyone.
I will setup a calendar server, but since I'm new to blockchain technology and I know it's internals only up to a certain point I'm wondering: if I use opentimestamp server with a pruned node that keeps, let's  say, only the last 550 blocks, would it be able to confirm a document whose hash was registered in a block before the last 550? 
Thanks for your help.

**Comment by RCasatta** [comment]
Hello,
pruned node is perfectly fine for opentimestamps.
The reason is it just needs block headers (of previously validated block).

Remember that you don't explicitly need a server to use opentimestamps, you can use the 4 public calendar servers. 
If you are concerned about public calendar servers availability, you can use your own as failover if none of the 4 public calendars servers is working. This would help minimize on-chain tx.

**Comment by petertodd** [comment]
Agreed.

Also, it's better for end users of your timestamps to use a public server unless you're consistently upgrading the timestamps after they're confirmed in the blockchain. Remember that a non-upgraded timestamp needs calendar data to be verified.

You can see this with the `ots info` command: try running it before and after `ots upgrade` is run.

**Comment by GTP95** [comment]
Thanks for your responses, I'm setting up a server because it will be used for a commercial project and I didn't want to abuse free resources. I was also unsure if it was legal at all, by a quick look on opentimestamps.org I didn't find any TOS for the public servers so I preferred not to risk. Maybe if you can confirm that I will not violate any TOS/license I could use my server as primary and the four public servers as fallback. By the way @petertodd what is the difference between an upgraded and a not upgraded timestamp and what do you mean by calendar data? My understanding is that once a document is registered onto the blockchain any calendar server should be able to verify it, but now I'm unsure. Do you have any documentation I can read to understand how timestamping works?

**Comment by petertodd** [comment]
Ah! I can confirm there is no terms-of-service for any of the public calendar servers. The only thing I'd ask is if you have very heavy load on them - *consistently* more than a few requests per second - you talk to us about mirroring/aggregation to reduce load on them.

Re: upgraded, that OTS timestamps start off with just the information necessary
to prove a "path" of operations to the calendars' per-second commitment. That
is *not* enough information to actually prove the timestamp is correct. After
the timestamp is created the calendars timestamp those commitments with
Bitcoin, and store those additional parts of the proof indefinitely. Upgrading
adds those additional proof operations to the .ots file, allowing the timestamp
proof to be verified without the aid of the calendars.

You might find my blog post helpful: https://petertodd.org/2016/opentimestamps-announcement

> Thanks for your responses, I'm setting up a server because it will be used for a commercial project and I didn't want to abuse free resources. I was also unsure if it was legal at all, by a quick look on opentimestamps.org I didn't find any TOS for the public servers so I preferred not to risk. Maybe if you can confirm that I will not violate any TOS/license I could use my server as primary and the four public servers as fallback. By the way @petertodd what is the difference between an upgraded and a not upgraded timestamp and what do you mean by calendar data? My understanding is that once a document is registered onto the blockchain any calendar server should be able to verify it, but now I'm unsure. Do you have any documentation I can read to understand how timestamping works?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/opentimestamps/opentimestamps-server/issues/74#issuecomment-592645942

-- 
https://petertodd.org 'peter'[:-1]@petertodd.org

**Comment by GTP95** [comment]
Thanks, I will definitely read your blogpost and if I still have questions I will open a separate issue. About the load it will be very light, no more than a few requests per day, and is not going to increase in the short term. It could increase in a year or two, but given the type of project is unlikely to
 reach multiple requests per second. Anyway if the traffic gets higher I will get in touch. Thanks for the clarifications.

**Comment by petertodd** [comment]
A few requests a day is no big deal - I estimate it costs the calendar servers
something like a millionth of a dollar to serve a request, so if you want to
pay up front for your next hundred years of usage just send us a few cents. :)

Good luck!

> Thanks, I will definitely read your blogpost and if I still have questions I will open a separate issue. About the load it will be very light, no more than a few requests per day, and is not going to increase in the short term. It could increase in a year or two, but given the type of project is unlikely to
>  reach multiple requests per second. Anyway if the traffic gets higher I will get in touch. Thanks for the clarifications.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/opentimestamps/opentimestamps-server/issues/74#issuecomment-592671271

-- 
https://petertodd.org 'peter'[:-1]@petertodd.org

**Comment by GTP95** [comment]
Thanks :)
I think I will use my server anyway since it gives me the possibility to generate a sort of certificate to send to the customer. It doesn't help the verification, but our customers would probably like a shiny PDF that says that their document has been registered. 
Have a nice weekend!
