### ISSUE TITLE
Opentimestamp server prevented wallet to see transaction

### ISSUE THREAD

**Issue by GTP95** [opentimestamps/opentimestamps-server#76]
Hello,
I'm running a public full node using bitcoin core v0.17.1 with the options deprecatedrpc=signrawtransaction deprecatedrpc=accounts addresstype=bech32 and otsd with only the --rpc-port option specified (I know that I can use the public servers but I've explained in another issue why I'll run my own server).
About two days ago I've transferred some funds from a coinbase account to the wallet on my server, and even if I was sure that the transaction was confirmed my node was showing the wallet as empty. You can read the details here: https://github.com/bitcoin-dot-org/bitcoin.org/issues/3299
Now (about two days after the transaction) I was trying to understand why the wallet wasn't up to date and I tried to run bitcoin-cli getblockchaininfo, stop opentimestamps server and run it again to see if I could determine if it was having some influence on bitcoin core. Sadly I don't know how to interpret getblockchaininfo's output so I wasn't able to see if there was an important difference, nor I have the output before and after stopping otsd (I've called getblockchaininfo multiple times and now I'm unable to tell which calls where while otsd was running and which while it wasn't); but after starting it again I saw that now my wallet  has the right balance:
```
$ bitcoin-cli getwalletinfo
{
  "walletname": "",
  "walletversion": 169900,
  "balance": 0.00228164,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 1,
[other fields omitted]
}
```
So seems that somehow otsd prevented the wallet from updating the balance. Is this a symptom of a configuration error on my side, a known problem or a new bug?

**Comment by petertodd** [comment]
Likely fixed by the latest version, which runs on recent versions of Bitcoin core.
