### ISSUE TITLE
Docker version of opentimestamps-server

### ISSUE THREAD

**Issue by march76** [opentimestamps/opentimestamps-server#79]
Hi everyone, is there a official docker version of the opentimestamps-server?
i find this diginex/opentimestamps-server on docker-hub...

**Comment by petertodd** [comment]
On Wed, Jul 01, 2020 at 05:23:47AM -0700, Marcello T. wrote:
> Hi everyone, is there a docker version of the opentimestamps-server?

There isn't an official one, and I'm not aware of any unofficial ones.
