### ISSUE TITLE
JSONRPCError while running bitcoin-core 0.21.1 version in regtest mode 

### ISSUE THREAD

**Issue by RebekkalPangras** [opentimestamps/opentimestamps-server#85]
Hi,

I use Bitcoin-0.21.1. Stamping happens correctly.
But during upgrade and verification I receive error.

__do_bitcoin() failed: JSONRPCError({'code': -32601, 'message': 'Method not found'})

**Comment by RCasatta** [comment]
Hi, at the moment the bitcoin node version supported is `0.17.1` as written in the Readme
