### ISSUE TITLE
BTC node and OTS server on different machines

### ISSUE THREAD

**Issue by RebekkalPangras** [opentimestamps/opentimestamps-server#86]
Hi, I am trying to create a custom calendar server. I currently have the bitcoin node in the same machine. And it works fine. Is it possible to run the Bitcoin node and the calendar server in different machines? How can we configure the calendar server to connect to the bitcoin node running in the other machine? Thanks

**Comment by RCasatta** [comment]
IIRC it reads the value in `~/.bitcoin/bitcoin.conf` so if you create a bitcoin.conf with the right parameters in the machine where there is the calendar it should work.

As a side note, there are 4 calendars on mainnet offering what we think is the best compromise between redundancy and space used on-chain. Anybody is obviously free to run his own calendar but it will not be added to the one included in the clients under the OpenTimestamps umbrella. 

Something interesting that doesn't exist yet would be a modified calendar software creating stamping txs only when it recognizes none of the 4 calendars made a recent stamping. This would remove the trust in the 4 calendars for anybody running it while avoiding writing too much in the main chain.

**Comment by RebekkalPangras** [comment]
Thanks for your quick response.
