### ISSUE TITLE
Calendar server is down

### ISSUE THREAD

**Issue by AnandakumarNatarajan** [opentimestamps/opentimestamps-server#99]
Hi Team,

One of the calendar servers https://bob.btc.calendar.opentimestamps.org/ is down it seems. 

Also, we are getting "Handshake failure" due to the recent SSL certificate(with EC signature algorithm) changes in the Alice server. 

Thanks,
Anand

**Comment by cisba** [comment]
FYI with the recent high fees the Bob OpenTimestamps calendar is stuck, pretty much out of money: bob.btc.calendar.opentimestamps.org

Donate via BTC or Lightning, and it'll get unstuck.

Source:
https://twitter.com/opentimestamps/status/1656051278105960456?s=19

**Comment by petertodd** [comment]
Back up.

Unusually this was a networking gltich: the server was running fine. But only
accessible via IPv6. For some reason the IPv4 networking failed. I have no idea
what went wrong. But resetting the VPS on Amazon seems to have fixed it.
